project_id = "dsnzmsiydwspatbflhrt"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54328
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[functions.achievement-tracker]
verify_jwt = false

[functions.generate-financial-statement]
verify_jwt = false

[functions.generate-receipt]
verify_jwt = false

[functions.generate-sales-report]
verify_jwt = false

[functions.initialize-trust-scores]
verify_jwt = false

[functions.inventory-insights]
verify_jwt = false

[functions.reminder-notifications]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.send-enquiry-email]
verify_jwt = false

[functions.send-product-request-email]
verify_jwt = false

[functions.supply-chain-analyzer]
verify_jwt = false