// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsnzmsiydwspatbflhrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzbnptc2l5ZHdzcGF0YmZsaHJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MDIzMzMsImV4cCI6MjA3NDI3ODMzM30.aQowJ_Gle2s4z38hrQiDEaweh9-vTK6cjJ5afltdYAw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});